import { Send, Square } from "lucide-react";
import type { Run } from "../../lib/types";

type Props = { mode: "coach" | "diagnosis"; setMode: (mode: "coach" | "diagnosis") => void; coachInput: string; setCoachInput: (value: string) => void; question: string; setQuestion: (value: string) => void; answer: string; setAnswer: (value: string) => void; followupId: string | null; activeRun: Run | null; readOnly: boolean; onSubmit: () => void; onCancel: () => void };

export function Composer(props: Props) {
  const disabled = Boolean(props.activeRun) || props.readOnly;
  return <div className="shrink-0 max-h-[52vh] overflow-y-auto border-t border-slate-200 bg-white px-4 py-4 sm:px-8"><div className="mx-auto max-w-3xl"><div className="mb-2 flex gap-1 text-xs" role="tablist" aria-label="工作模式"><button type="button" role="tab" aria-selected={props.mode === "coach"} onClick={() => props.setMode("coach")} disabled={disabled} className={`border px-3 py-1.5 ${props.mode === "coach" ? "border-slate-900 bg-slate-900 text-white" : "border-slate-300 text-slate-600"}`}>练习对话</button><button type="button" role="tab" aria-selected={props.mode === "diagnosis"} onClick={() => props.setMode("diagnosis")} disabled={disabled} className={`border px-3 py-1.5 ${props.mode === "diagnosis" ? "border-slate-900 bg-slate-900 text-white" : "border-slate-300 text-slate-600"}`}>正式诊断</button></div>{props.mode === "coach" ? <textarea aria-label="练习输入" aria-keyshortcuts="Control+Enter Meta+Enter" value={props.coachInput} onChange={(event) => props.setCoachInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) props.onSubmit(); }} disabled={disabled} rows={3} placeholder="输入练习目标或追问方向" className="w-full resize-y border border-slate-300 bg-white p-3 text-sm outline-none focus:border-primary-500" /> : <div className="space-y-2"><textarea aria-label="面试题" value={props.question} onChange={(event) => props.setQuestion(event.target.value)} disabled={disabled} rows={2} placeholder="面试题" className="w-full resize-y border border-slate-300 p-3 text-sm outline-none focus:border-primary-500" /><textarea aria-label="候选人回答" value={props.answer} onChange={(event) => props.setAnswer(event.target.value)} disabled={disabled} rows={4} placeholder="候选人回答" className="w-full resize-y border border-slate-300 p-3 text-sm outline-none focus:border-primary-500" />{props.followupId && <p className="text-xs text-primary-700">本次提交将回答所选追问。</p>}</div>}<div className="mt-2 flex items-center justify-between">{props.readOnly ? <p className="text-[11px] text-slate-400">归档会话只读</p> : <span aria-hidden="true" />}<div className="flex gap-2">{props.activeRun && <button type="button" onClick={props.onCancel} className="flex items-center gap-1 border border-red-300 px-3 py-1.5 text-sm text-red-700" aria-label="停止运行"><Square size={13} aria-hidden="true" />停止</button>}<button type="button" onClick={props.onSubmit} disabled={disabled || (props.mode === "coach" ? !props.coachInput.trim() : !props.question.trim() || !props.answer.trim())} className="flex items-center gap-1 bg-slate-900 px-4 py-1.5 text-sm text-white disabled:bg-slate-300">{props.activeRun ? "运行中" : props.mode === "coach" ? <><Send size={14} aria-hidden="true" />发送</> : "开始诊断"}</button></div></div></div></div>;
}
